# Configuration for local development
version: '3'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8888:80
